name: Run tests

description: Run project's unit tests using Jest Node testing framework

runs:
  using: "composite"
  steps:
    - name: Run unit tests using vitest framework
      shell: bash
      run: npm run test
