name: Build and deploy to github pages with CI/CD

on:
    push:
        branches:
            - main

env:
  node-version: 21.x
  working-directory: ./

permissions:
    contents: read
    pages: write
    id-token: write
    


jobs:
    test-build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Use Node.js ${{ env.node-version }}
              uses: ./.github/actions/setup-node
              with:
                node-version: ${{ env.node-version }}

            - name: Install Node modules
              uses: ./.github/actions/install-node-modules
        
            - name: Run tests using the vitest framework
              uses: ./.github/actions/run-tests

            - name: Build App
              uses: ./.github/actions/build-app

            - name: Upload production-ready build files
              uses: actions/upload-artifact@v2
              with:
                name: production-files
                path: ./dist

    deploy:
      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Set up Node
          uses: actions/setup-node@v4
          with:
            node-version: 20
            cache: 'npm'
        - name: Install dependencies
          run: npm ci
        - name: Build
          run: npm run build
        - name: Setup Pages
          uses: actions/configure-pages@v4
          with:
            enablement: true
        - name: Upload artifact
          uses: actions/upload-pages-artifact@v3
          with:
            # Upload dist folder
            path: './dist'
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v4
          

