name: Build and deploy to github pages with CI/CD

on:
    push:
        branches:
            - main

env:
  node-version: 21.x
  working-directory: ./

permissions:
    contents: read
    pages: write
    id-token: write


jobs:
    test-build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Use Node.js ${{ env.node-version }}
              uses: ./.github/actions/setup-node
              with:
                node-version: ${{ env.node-version }}

            - name: Install Node modules
              uses: ./.github/actions/install-node-modules
        
            - name: Run tests using the vitest framework
              uses: ./.github/actions/run-tests

            - name: Build App
              uses: ./.github/actions/build-app

            - name: Upload production-ready build files
              uses: actions/upload-artifact@v2
              with:
                name: production-files
                path: ./dist

    deploy:
      name: Deploy
      needs: test-build
      runs-on: ubuntu-latest
      if: github.ref == 'refs/heads/main'

      steps:
          - name: Download artifact
            uses: actions/download-artifact@v2
            with:
                name: production-files
                path: ./dist

          - name: Deploy to GitHub Pages
            uses: peaceiris/actions-gh-pages@v4
            with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./dist

